app:
  env: test
  name: go-mall
  log:
    path: "C:/logs/go-mall.log"
    max_size: 100
    max_age: 60
  pagination:
    default_size: 20
    max_size: 100

database:
  type: mysql
  master:
    dsn: root:superpass@tcp(localhost:13306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen : 100
    maxidle: 10
    maxlifetime: 300000000 # 300s内空闲连接复用
  slave:
    dsn: root:superpass@tcp(localhost:13306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000 # 300s内空闲连接复用

redis:
  addr: localhost:16379
  password: 123456
  pool_size: 10
  db: 0