app:
  env: dev
  name: go-mall
  log:
    path: "C:/logs/testing/go-mall.log"
    max_size: 1
    max_age: 60
  pagination:
    default_size: 20
    max_size: 100

database:
  master:
    type: mysql
    dsn: root:superpass@tcp(localhost:13306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen : 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s内空闲连接复用
  slave:
    type: mysql
    dsn: root:superpass@tcp(localhost:13306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s内空闲连接复用

  pg_master:
    type: postgres
    dsn: host=localhost user=postgres password=S@lnyw0000 dbname=go_mall port=15432 sslmode=disable TimeZone=Asia/Shanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s内空闲连接复用

  pg_slave:
    type: postgres
    dsn: host=localhost user=postgres password=S@lnyw0000 dbname=go_mall port=15432 sslmode=disable TimeZone=Asia/Shanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s内空闲连接复用

redis:
  addr: localhost:16379
  password: 123456
  pool_size: 10
  db: 0